Feature/122 unit tests for strings
aregtech/areg-sdk pull request #124
Opened 2023-02-15 01:14 UTC by harshit496

2023-02-15 12:25 UTC, aregtech requested changes
@harshit496 ,
thank you for changes. It is a good start.
Please let's keep same / similar syntax, be closer to C++17 and avoid testings, which give nothing.
I avoid using `typeid`, `dynamic_cast` and `try-catch` blocks, because they increase the size of binaries. As well as if a returns type is `int`, there is no need to check the type.
Please do not hesitate to discuss if you other opinion. I'm open to listen and get better ideas.

2023-02-15 12:25 UTC, aregtech commented on tests/units/StringTest.cpp
>  TEST(StringTest, makeInt32)
- Please add comment for the test.
- Please add `Test` prefix to the method.

2023-02-15 12:25 UTC, aregtech commented on tests/units/StringTest.cpp
>      int32_t result_int32 = 52;
For both cases please use `constexpr`

2023-02-15 12:25 UTC, aregtech commented on tests/units/StringTest.cpp
>      EXPECT_EQ(typeid(String::makeInt32(test)), typeid(result_int32));
No need to test `typeid`.
Avoid using `typeid`, `dynamic_cast` and `exception` whenever it is possible. Only if there is a real need.

2023-02-15 12:25 UTC, aregtech commented on tests/units/StringTest.cpp
> +    uint32_t result_uint32 = 52;
For both variables, please use `consexpr`

2023-02-15 12:25 UTC, aregtech commented on tests/units/StringTest.cpp
> +TEST(StringTest, makeUInt32)
- Please comment the test.
- Please add a `Test` prefix to the method.

2023-02-15 12:25 UTC, aregtech commented on tests/units/StringTest.cpp
> +    EXPECT_NE(typeid(String::makeUInt32(test)), typeid(result_uint16));
No need for `typeid`

2023-03-11 13:47 UTC, aregtech commented
Hello @harshit496 
do you still have interest to write unit tests?

2023-03-15 03:36 UTC, harshit496 commented
Hi @aregtech sorry I was traveling so couldn't get to it. I can pick it up now. Thanks for the reminder and sorry for delaying this.

2023-03-21 01:02 UTC, aregtech approved these changes
Thank you, @harshit496 
It is a good start.

2023-03-21 01:02 UTC, aregtech commented on tests/units/StringTest.cpp
> +TEST(StringTest, getSubstring)
Please comment the test and add `Test` prefix.

2023-03-21 01:03 UTC, merged

2023-03-23 16:00 UTC, harshit496 commented
Thanks! Although @aregtech I actually had some more tests that weren't committed. Nvm I will get them in another MR then