NESocket - Use std::string instead of String
aregtech/areg-sdk pull request #43
Opened 2022-02-07 14:06 UTC by biwiki

=== Not ready to merge yet ===
Converting String to std::string in the areg base can be done incrementally like this.
Still not compatible, but it is quite promising that we can move to std::string step by step.

2022-02-07 15:42 UTC, aregtech commented on framework/areg/base/private/SocketClient.cpp
> +        SOCKETHANDLE hSocket = NESocket::clientSocketConnect(mAddress.getHostAddress().c_str(), mAddress.getHostPort());
This is OK. But when we complete converting to `std::string`, we'll need to convert `const char *` in function parameters into `std::string_view` or `const std::string &`. 
At the moment it is fine and I leave like it is.

2022-02-07 15:47 UTC, aregtech commented
@biwiki, thank you for changes.
The MS Build fails. The line 227 in NESocket.cpp file --> please change `.isEmpty()` ==> `.empty()`.
It is MS VS specific code and do not see when compile with GCC.

2022-02-07 15:48 UTC, aregtech requested changes
Please check MS Build.
File NESocket.cpp, line 227 is MS VS specific code --> `isEmpty()` method does not exist.

2022-02-08 12:58 UTC, biwiki commented
@aregtech Yes, this PR breaks the build, thus it is not ready to merge.
In fact, this is a tiny demonstration for the approach that we can use to convert String to std::string.

2022-02-08 14:48 UTC, biwiki commented on framework/areg/base/private/SocketClient.cpp
> +        SOCKETHANDLE hSocket = NESocket::clientSocketConnect(mAddress.getHostAddress().c_str(), mAddress.getHostPort());
ACKed

2022-02-08 14:57 UTC, biwiki commented
@aregtech please take another look at this PR, thanks!

2022-02-08 16:25 UTC, aregtech approved these changes
Thank you!

2022-02-08 16:25 UTC, merged